from conn_template import *

CONN_POINT_1 = CONN(CONN_MANIFOLD_DIM.CONN_1_MANIFOLD, 1, 1)
cloned_CONN_POINT_1 = CONN_POINT_1.clone()

assert(CONN_POINT_1.MANIFOLD_DIM == cloned_CONN_POINT_1.MANIFOLD_DIM)
assert(CONN_POINT_1.NFENS == cloned_CONN_POINT_1.NFENS)
assert(CONN_POINT_1.NREFFENS == cloned_CONN_POINT_1.NREFFENS)
